name: Auto Tagging Submodule After Release

on:
  release:
    types: [ created ]

jobs:
  tag_push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Log information about the pull request
        run: |
          echo "Comment: ${{ github.event.comment.body }}"
          echo "Event name: ${{ github.event_name }}"
          echo "Pull request merged: ${{ github.event.pull_request.merged }}"
          echo "Actor: ${{ github.actor }}"
          echo "PR Title: ${{ github.event.pull_request.title }}"
          echo "Bump PR: ${{ contains(github.event.pull_request.title, 'bump') }}"
          echo "Dependabot PR: ${{ contains(github.event.pull_request.title, 'dependabot') }}"
      - name: Checkout code
        uses: actions/checkout@v4.2.0 # v4
        with:
          ref: main
          fetch-depth: 0 # Fetch all history
      - name: Run tag script
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          chmod +x ./.github/scripts/tag.sh
          ./.github/scripts/tag.sh
      - name: Commit and push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git push origin --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      - name: Upload assets
#        uses: actions/upload-artifact@v4.4.3
#        with:
#          name: protoc-gen-go-gins
#          path: ./cmd/protoc-gen-go-gins/dist/*
